### ISSUE TITLE
Requires file what_I_have.yaml

### ISSUE THREAD

**Issue by dangrec** [goskas/Incompetech-Bulk-Downloader#1]
Hi There,

Upon running the script I get the following:
IOError: [Errno 2] No such file or directory: 'what_I_have.yaml'

I tried creating an empty file with that name, but had no luck.

Can you please provide details about what that file needs to contain to get this script running for the first time?

Thanks,

**Comment by goskas** [comment]
Hello.

Hmm. I kind of  did this program in a hurry and never got around to making it prettier. I'm currently traveling, so I don't know how much I can help.

Did you make the what_I_have.yaml file in the same directory as is the incompetech_music_downloader.py ? Could you also try making one empty line in the file? Otherwise you can try setting the content to:

```
USUAN1100001:
  BPM: '117'
  Collection: Funk and Blues
  Duration: '2:50'
  Duration_seconds: 170
  Genre: Funk
  Instruments:
  - Bass
  - Kit
  - Guitar
  - Bari Sax
  - Tenor Sax
  - Trumpet
  - Percussion
  URL: /music/royalty-free/index.html?isrc=USUAN1100001&Search=Search
  name: C-Funk
  size: 6.625 MB
```

That should download all songs except this one.

Now that I'm looking at the code, you should probably change
'if **name** == '**main**' and 0:' to
'if **name** == '**main**' and 1:'
in line 198.

I hope this helps.
